name: 'Setup bun'
inputs:
  bun_version:
    required: false
    default: '1.4.2'

runs:
  using: 'composite'
  steps:
    - name: Set up Bun ${{ inputs.bun_version }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun_version }}

    - name: Install dependencies
      shell: bash
      run: |
        bun install --frozen-lockfile
        bun run prisma:generate
      env:
        HUSKY: '0'
